#!/bin/sh
LOGS_DIR="logs"
PID_FILE="logs/pid.log"
APP_NAME="wallpaper-changer"

case "$1" in
start)
  if [ ! -d "$LOGS_DIR" ]; then
    mkdir "$LOGS_DIR";
  fi
  nohup sh app.sh > logs/app.log 2>&1 &
  echo $! > logs/pid.log
  ;;
stop)
  if [ -e "$PID_FILE" ]; then
    cat "$PID_FILE" | while read PID; do
      kill -9 "$PID";
      rm "$PID_FILE";
    done
  else
    echo "$APP_NAME" is not running
    exit 1
  fi
  ;;
restart)
  $0 stop
  $0 start
  ;;
status)
  if [ -e "$PID_FILE" ]; then
    echo "$APP_NAME" is running, pid=`cat "$PID_FILE"`
  else
    echo "$APP_NAME" is not running
    exit 1
  fi
  ;;
*)
  echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
